acme_topic:
    channel: acme/channel/{userId}
    handler:
        callback: 'acme.topic' #related to the getName() of your topic
    requirements:
#            room:
#                pattern: "[a-z]+" #accept all valid regex, don't put delimiters !
            userId:
                pattern: "\d+"

acme_rpc:
    channel: sample/{method}
    handler:
        callback: 'acme.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+"